name: PHP Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: wordpress_test
      DB_USER: root
      DB_PASSWORD: root
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2', '8.3', '8.4']
        wp-versions: [ '6.5', '6.6', '6.7', 'latest', 'trunk' ]
    name: WP ${{ matrix.wp-versions }} / PHP ${{ matrix.php-versions }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Install Subversion.
      run: |
        sudo apt-get update -y
        sudo apt-get install -y subversion

    - name: Check PHP Version
      run: php -v

    - name: Composer install
      run: composer install --optimize-autoloader --prefer-dist

    - name: Install WP Tests
      run: |
        sudo /etc/init.d/mysql start
        bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wp-versions }}

    - name: PHPUnit tests
      run: ./vendor/bin/phpunit
      env:
        WP_TESTS_DIR: ${{ runner.temp }}/wordpress-tests-lib
        WP_CORE_DIR: ${{ runner.temp }}/wordpress

  required-status-checks:
    # This should be configured as the required status check in branch protection rules
    #
    # Using a summary job allows for easier management of the PHP Unit matrix as the
    # required status check will not need to be updated when matrix items change.
    name: PHPUnit Required Status Checks
    runs-on: 'ubuntu-24.04'
    needs: [ 'phpunit' ]
    if: ${{ always() }}
    steps:
      - name: Detect any failing status checks
        run: |
          [[ "${{ join(needs.*.result, ' ') }}" =~ ^(success ?)+$ ]] || exit 1
