name: "WordPress version checker"
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

permissions:
  issues: write

jobs:
  wordpress-version-checker:
    runs-on: ubuntu-latest
    steps:
      - name: WordPress version checker
        uses: skaut/wordpress-version-checker@9d247334f5b30202cb9c1f4aee74c52f37399f69 # 2.2.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
