name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  update_assets:
    # Disable workflow until release on WordPress.org
    if: false
    name: Push asset update to WordPress.org
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Create .wordpress-org directory if it doesn't exist.
      run: mkdir -p .wordpress-org

    - name: Remove readme.md from WordPress.org deploy.
      run: |
        git rm readme.md
        git config --global user.email "10upbot+github@10up.com"
        git config --global user.name "10upbot on GitHub"
        git commit -m "Remove readme.md for WordPress.org deploy"

    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
