name: Deploy to WordPress.org Repository

on:
  release:
    types: [released]

jobs:
  deploy_to_wp_repository:
    # Disable workflow until release on WordPress.org
    if: false
    name: Deploy to WP.org
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Subversion.
      run: |
        # Check if SVN is installed, if not install it.
        if ! command -v svn &> /dev/null
        then
            sudo apt-get update -y
            sudo apt-get install -y subversion
        fi

    - name: Remove readme.md from WordPress.org deploy.
      run: |
        git rm readme.md
        git config --global user.email "10upbot+github@10up.com"
        git config --global user.name "10upbot on GitHub"
        git commit -m "Remove readme.md for WordPress.org deploy"

    - name: Create .wordpress-org directory if it doesn't exist.
      run: mkdir -p .wordpress-org

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true

      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
